## static_territories
UPDATE static_territories SET tr_name_de='Afrika',tr_iso_nr='2' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_de='Ozeanien',tr_iso_nr='9' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_de='Nord-, Mittel- und Südamerika',tr_iso_nr='19' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_de='Asien',tr_iso_nr='142' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_de='Europa',tr_iso_nr='150' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_de='Ostasien',tr_iso_nr='30' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_de='Südostasien',tr_iso_nr='35' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_de='Süd-Zentralasien',tr_iso_nr='62' WHERE tr_iso_nr='62';
UPDATE static_territories SET tr_name_de='Westasien',tr_iso_nr='145' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_de='Südeuropa',tr_iso_nr='39' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_de='Osteuropa',tr_iso_nr='151' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_de='Nordeuropa',tr_iso_nr='154' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_de='Westeuropa',tr_iso_nr='155' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_de='Kanalinseln',tr_iso_nr='830' WHERE tr_iso_nr='830';
UPDATE static_territories SET tr_name_de='Insel Man',tr_iso_nr='833' WHERE tr_iso_nr='833';
UPDATE static_territories SET tr_name_de='Südamerika',tr_iso_nr='5' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_de='Mittelamerika',tr_iso_nr='13' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_de='Nordamerika',tr_iso_nr='21' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_de='Karibik',tr_iso_nr='29' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_de='Westafrika',tr_iso_nr='11' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_de='Ostafrika',tr_iso_nr='14' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_de='Nordafrika',tr_iso_nr='15' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_de='Zentralafrika',tr_iso_nr='17' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_de='Südafrika',tr_iso_nr='18' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_de='Australien und Neuseeland',tr_iso_nr='53' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_de='Melanesien',tr_iso_nr='54' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_de='Mikronesien',tr_iso_nr='57' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_de='Polynesien',tr_iso_nr='61' WHERE tr_iso_nr='61';


## static_countries
UPDATE static_countries SET cn_short_de='Andorra',cn_iso_2='AD' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_de='Vereinigte Arabische Emirate',cn_iso_2='AE' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_de='Afghanistan',cn_iso_2='AF' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_de='Antigua und Barbuda',cn_iso_2='AG' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_de='Anguilla',cn_iso_2='AI' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_de='Albanien',cn_iso_2='AL' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_de='Armenien',cn_iso_2='AM' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_de='Niederländische Antillen',cn_iso_2='AN' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_de='Angola',cn_iso_2='AO' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_de='Antarktis',cn_iso_2='AQ' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_de='Argentinien',cn_iso_2='AR' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_de='Amerikanisch-Samoa',cn_iso_2='AS' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_de='Österreich',cn_iso_2='AT' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_de='Australien',cn_iso_2='AU' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_de='Aruba',cn_iso_2='AW' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_de='Aserbaidschan',cn_iso_2='AZ' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_de='Bosnien und Herzegowina',cn_iso_2='BA' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_de='Barbados',cn_iso_2='BB' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_de='Bangladesch',cn_iso_2='BD' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_de='Belgien',cn_iso_2='BE' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_de='Burkina Faso',cn_iso_2='BF' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_de='Bulgarien',cn_iso_2='BG' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_de='Bahrain',cn_iso_2='BH' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_de='Burundi',cn_iso_2='BI' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_de='Benin',cn_iso_2='BJ' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_de='Bermuda',cn_iso_2='BM' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_de='Brunei Darussalam',cn_iso_2='BN' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_de='Bolivien',cn_iso_2='BO' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_de='Brasilien',cn_iso_2='BR' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_de='Bahamas',cn_iso_2='BS' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_de='Bhutan',cn_iso_2='BT' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_de='Bouvetinsel',cn_iso_2='BV' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_de='Botsuana',cn_iso_2='BW' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_de='Belarus',cn_iso_2='BY' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_de='Belize',cn_iso_2='BZ' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_de='Kanada',cn_iso_2='CA' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_de='Kokosinseln (Keeling)',cn_iso_2='CC' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_de='Demokratische Republik Kongo',cn_iso_2='CD' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_de='Zentralafrikanische Republik',cn_iso_2='CF' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_de='Kongo',cn_iso_2='CG' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_de='Schweiz',cn_iso_2='CH' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_de='Côte d’Ivoire',cn_iso_2='CI' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_de='Cookinseln',cn_iso_2='CK' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_de='Chile',cn_iso_2='CL' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_de='Kamerun',cn_iso_2='CM' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_de='China',cn_iso_2='CN' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_de='Kolumbien',cn_iso_2='CO' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_de='Costa Rica',cn_iso_2='CR' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_de='Kuba',cn_iso_2='CU' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_de='Kap Verde',cn_iso_2='CV' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_de='Weihnachtsinsel',cn_iso_2='CX' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_de='Zypern',cn_iso_2='CY' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_de='Tschechische Republik',cn_iso_2='CZ' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_de='Deutschland',cn_iso_2='DE' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_de='Dschibuti',cn_iso_2='DJ' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_de='Dänemark',cn_iso_2='DK' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_de='Dominica',cn_iso_2='DM' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_de='Dominikanische Republik',cn_iso_2='DO' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_de='Algerien',cn_iso_2='DZ' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_de='Ecuador',cn_iso_2='EC' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_de='Estland',cn_iso_2='EE' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_de='Ägypten',cn_iso_2='EG' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_de='Westsahara',cn_iso_2='EH' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_de='Eritrea',cn_iso_2='ER' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_de='Spanien',cn_iso_2='ES' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_de='Äthiopien',cn_iso_2='ET' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_de='Finnland',cn_iso_2='FI' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_de='Fidschi',cn_iso_2='FJ' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_de='Falklandinseln',cn_iso_2='FK' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_de='Mikronesien',cn_iso_2='FM' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_de='Färöer',cn_iso_2='FO' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_de='Frankreich',cn_iso_2='FR' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_de='Gabun',cn_iso_2='GA' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_de='Vereinigtes Königreich',cn_iso_2='GB' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_de='Grenada',cn_iso_2='GD' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_de='Georgien',cn_iso_2='GE' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_de='Französisch-Guayana',cn_iso_2='GF' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_de='Ghana',cn_iso_2='GH' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_de='Gibraltar',cn_iso_2='GI' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_de='Grönland',cn_iso_2='GL' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_de='Gambia',cn_iso_2='GM' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_de='Guinea',cn_iso_2='GN' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_de='Guadeloupe',cn_iso_2='GP' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_de='Äquatorialguinea',cn_iso_2='GQ' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_de='Griechenland',cn_iso_2='GR' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_de='Südgeorgien und die Südlichen Sandwichinseln',cn_iso_2='GS' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_de='Guatemala',cn_iso_2='GT' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_de='Guam',cn_iso_2='GU' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_de='Guinea-Bissau',cn_iso_2='GW' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_de='Guyana',cn_iso_2='GY' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_de='Hong Kong S.A.R., China',cn_iso_2='HK' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_de='Honduras',cn_iso_2='HN' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_de='Kroatien',cn_iso_2='HR' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_de='Haiti',cn_iso_2='HT' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_de='Ungarn',cn_iso_2='HU' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_de='Indonesien',cn_iso_2='ID' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_de='Irland',cn_iso_2='IE' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_de='Israel',cn_iso_2='IL' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_de='Indien',cn_iso_2='IN' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_de='Britisches Territorium im Indischen Ozean',cn_iso_2='IO' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_de='Irak',cn_iso_2='IQ' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_de='Iran',cn_iso_2='IR' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_de='Island',cn_iso_2='IS' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_de='Italien',cn_iso_2='IT' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_de='Jamaika',cn_iso_2='JM' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_de='Jordanien',cn_iso_2='JO' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_de='Japan',cn_iso_2='JP' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_de='Kenia',cn_iso_2='KE' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_de='Kirgisistan',cn_iso_2='KG' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_de='Kambodscha',cn_iso_2='KH' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_de='Kiribati',cn_iso_2='KI' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_de='Komoren',cn_iso_2='KM' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_de='St. Kitts und Nevis',cn_iso_2='KN' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_de='Demokratische Volksrepublik Korea',cn_iso_2='KP' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_de='Republik Korea',cn_iso_2='KR' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_de='Kuwait',cn_iso_2='KW' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_de='Kaimaninseln',cn_iso_2='KY' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_de='Kasachstan',cn_iso_2='KZ' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_de='Laos',cn_iso_2='LA' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_de='Libanon',cn_iso_2='LB' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_de='St. Lucia',cn_iso_2='LC' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_de='Liechtenstein',cn_iso_2='LI' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_de='Sri Lanka',cn_iso_2='LK' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_de='Liberia',cn_iso_2='LR' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_de='Lesotho',cn_iso_2='LS' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_de='Litauen',cn_iso_2='LT' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_de='Luxemburg',cn_iso_2='LU' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_de='Lettland',cn_iso_2='LV' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_de='Libyen',cn_iso_2='LY' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_de='Marokko',cn_iso_2='MA' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_de='Monaco',cn_iso_2='MC' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_de='Republik Moldau',cn_iso_2='MD' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_de='Madagaskar',cn_iso_2='MG' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_de='Marshallinseln',cn_iso_2='MH' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_de='Mazedonien',cn_iso_2='MK' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_de='Mali',cn_iso_2='ML' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_de='Myanmar',cn_iso_2='MM' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_de='Mongolei',cn_iso_2='MN' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_de='Macau S.A.R., China',cn_iso_2='MO' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_de='Nördliche Marianen',cn_iso_2='MP' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_de='Martinique',cn_iso_2='MQ' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_de='Mauretanien',cn_iso_2='MR' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_de='Montserrat',cn_iso_2='MS' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_de='Malta',cn_iso_2='MT' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_de='Mauritius',cn_iso_2='MU' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_de='Malediven',cn_iso_2='MV' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_de='Malawi',cn_iso_2='MW' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_de='Mexiko',cn_iso_2='MX' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_de='Malaysia',cn_iso_2='MY' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_de='Mosambik',cn_iso_2='MZ' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_de='Namibia',cn_iso_2='NA' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_de='Neukaledonien',cn_iso_2='NC' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_de='Niger',cn_iso_2='NE' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_de='Norfolkinsel',cn_iso_2='NF' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_de='Nigeria',cn_iso_2='NG' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_de='Nicaragua',cn_iso_2='NI' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_de='Niederlande',cn_iso_2='NL' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_de='Norwegen',cn_iso_2='NO' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_de='Nepal',cn_iso_2='NP' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_de='Nauru',cn_iso_2='NR' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_de='Niue',cn_iso_2='NU' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_de='Neuseeland',cn_iso_2='NZ' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_de='Oman',cn_iso_2='OM' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_de='Panama',cn_iso_2='PA' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_de='Peru',cn_iso_2='PE' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_de='Französisch-Polynesien',cn_iso_2='PF' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_de='Papua-Neuguinea',cn_iso_2='PG' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_de='Philippinen',cn_iso_2='PH' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_de='Pakistan',cn_iso_2='PK' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_de='Polen',cn_iso_2='PL' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_de='St. Pierre und Miquelon',cn_iso_2='PM' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_de='Pitcairn',cn_iso_2='PN' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_de='Puerto Rico',cn_iso_2='PR' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_de='Portugal',cn_iso_2='PT' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_de='Palau',cn_iso_2='PW' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_de='Paraguay',cn_iso_2='PY' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_de='Katar',cn_iso_2='QA' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_de='Réunion',cn_iso_2='RE' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_de='Rumänien',cn_iso_2='RO' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_de='Russische Föderation',cn_iso_2='RU' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_de='Ruanda',cn_iso_2='RW' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_de='Saudi-Arabien',cn_iso_2='SA' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_de='Salomonen',cn_iso_2='SB' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_de='Seychellen',cn_iso_2='SC' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_de='Sudan',cn_iso_2='SD' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_de='Schweden',cn_iso_2='SE' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_de='Singapur',cn_iso_2='SG' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_de='St. Helena',cn_iso_2='SH' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_de='Slowenien',cn_iso_2='SI' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_de='Svalbard und Jan Mayen',cn_iso_2='SJ' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_de='Slowakei',cn_iso_2='SK' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_de='Sierra Leone',cn_iso_2='SL' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_de='San Marino',cn_iso_2='SM' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_de='Senegal',cn_iso_2='SN' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_de='Somalia',cn_iso_2='SO' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_de='Suriname',cn_iso_2='SR' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_de='São Tomé und Príncipe',cn_iso_2='ST' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_de='El Salvador',cn_iso_2='SV' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_de='Syrien',cn_iso_2='SY' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_de='Swasiland',cn_iso_2='SZ' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_de='Turks- und Caicosinseln',cn_iso_2='TC' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_de='Tschad',cn_iso_2='TD' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_de='Französische Süd- und Antarktisgebiete',cn_iso_2='TF' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_de='Togo',cn_iso_2='TG' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_de='Thailand',cn_iso_2='TH' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_de='Tadschikistan',cn_iso_2='TJ' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_de='Tokelau',cn_iso_2='TK' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_de='Turkmenistan',cn_iso_2='TM' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_de='Tunesien',cn_iso_2='TN' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_de='Tonga',cn_iso_2='TO' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_de='Osttimor',cn_iso_2='TL' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_de='Türkei',cn_iso_2='TR' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_de='Trinidad und Tobago',cn_iso_2='TT' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_de='Tuvalu',cn_iso_2='TV' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_de='Taiwan',cn_iso_2='TW' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_de='Tansania',cn_iso_2='TZ' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_de='Ukraine',cn_iso_2='UA' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_de='Uganda',cn_iso_2='UG' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_de='Amerikanisch-Ozeanien',cn_iso_2='UM' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_de='Vereinigte Staaten',cn_iso_2='US' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_de='Uruguay',cn_iso_2='UY' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_de='Usbekistan',cn_iso_2='UZ' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_de='Vatikanstadt',cn_iso_2='VA' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_de='St. Vincent und die Grenadinen',cn_iso_2='VC' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_de='Venezuela',cn_iso_2='VE' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_de='Britische Jungferninseln',cn_iso_2='VG' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_de='Amerikanische Jungferninseln',cn_iso_2='VI' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_de='Vietnam',cn_iso_2='VN' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_de='Vanuatu',cn_iso_2='VU' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_de='Wallis und Futuna',cn_iso_2='WF' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_de='Samoa',cn_iso_2='WS' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_de='Jemen',cn_iso_2='YE' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_de='Mayotte',cn_iso_2='YT' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_de='Südafrika',cn_iso_2='ZA' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_de='Sambia',cn_iso_2='ZM' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_de='Simbabwe',cn_iso_2='ZW' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_de='Palästinensische Gebiete',cn_iso_2='PS' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_de='Serbien und Montenegro',cn_iso_2='CS' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_de='Alandinseln',cn_iso_2='AX' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_de='Heard und McDonaldinseln',cn_iso_2='HM' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_de='Äußeres Ozeanien',cn_iso_2='QO' WHERE cn_iso_2='QO';


## static_country_zones


## static_currencies
UPDATE static_currencies SET cu_name_de='UAE Dirham',cu_sub_name_de='',cu_iso_3='AED' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_de='Lek',cu_sub_name_de='',cu_iso_3='ALL' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_de='Dram',cu_sub_name_de='',cu_iso_3='AMD' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_de='Niederl. Antillen Gulden',cu_sub_name_de='',cu_iso_3='ANG' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_de='Kwanza',cu_sub_name_de='',cu_iso_3='AOA' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_de='Argentinischer Peso',cu_sub_name_de='',cu_iso_3='ARS' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_de='Australischer Dollar',cu_sub_name_de='',cu_iso_3='AUD' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_de='Aruba Florin',cu_sub_name_de='',cu_iso_3='AWG' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_de='Aserbeidschan Manat',cu_sub_name_de='',cu_iso_3='AZM' WHERE cu_iso_3='AZM';
UPDATE static_currencies SET cu_name_de='Konvertierbare Mark',cu_sub_name_de='',cu_iso_3='BAM' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_de='Barbados-Dollar',cu_sub_name_de='',cu_iso_3='BBD' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_de='Taka',cu_sub_name_de='',cu_iso_3='BDT' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_de='Lew',cu_sub_name_de='',cu_iso_3='BGN' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_de='Bahrain-Dinar',cu_sub_name_de='',cu_iso_3='BHD' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_de='Burundi-Franc',cu_sub_name_de='',cu_iso_3='BIF' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_de='Bermuda-Dollar',cu_sub_name_de='',cu_iso_3='BMD' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_de='Brunei-Dollar',cu_sub_name_de='',cu_iso_3='BND' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_de='Boliviano',cu_sub_name_de='',cu_iso_3='BOB' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_de='Real',cu_sub_name_de='',cu_iso_3='BRL' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_de='Bahama-Dollar',cu_sub_name_de='',cu_iso_3='BSD' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_de='Ngultrum',cu_sub_name_de='',cu_iso_3='BTN' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_de='Pula',cu_sub_name_de='',cu_iso_3='BWP' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_de='Belarus Rubel (neu)',cu_sub_name_de='',cu_iso_3='BYR' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_de='Belize-Dollar',cu_sub_name_de='',cu_iso_3='BZD' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_de='Kanadischer Dollar',cu_sub_name_de='',cu_iso_3='CAD' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_de='Franc congolais',cu_sub_name_de='',cu_iso_3='CDF' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_de='Schweizer Franken',cu_sub_name_de='',cu_iso_3='CHF' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_de='Chilenischer Peso',cu_sub_name_de='',cu_iso_3='CLP' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_de='Renminbi Yuan',cu_sub_name_de='',cu_iso_3='CNY' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_de='Kolumbianischer Peso',cu_sub_name_de='',cu_iso_3='COP' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_de='Costa Rica Colon',cu_sub_name_de='',cu_iso_3='CRC' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_de='Kubanischer Peso',cu_sub_name_de='',cu_iso_3='CUP' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_de='Kap Verde Escudo',cu_sub_name_de='',cu_iso_3='CVE' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_de='Zypern Pfund',cu_sub_name_de='',cu_iso_3='CYP' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_de='Tschechische Krone',cu_sub_name_de='',cu_iso_3='CZK' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_de='Dschibuti-Franc',cu_sub_name_de='',cu_iso_3='DJF' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_de='Dänische Krone',cu_sub_name_de='',cu_iso_3='DKK' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_de='Dominikanischer Peso',cu_sub_name_de='',cu_iso_3='DOP' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_de='Algerischer Dinar',cu_sub_name_de='',cu_iso_3='DZD' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_de='Estnische Krone',cu_sub_name_de='',cu_iso_3='EEK' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_de='Ägyptisches Pfund',cu_sub_name_de='',cu_iso_3='EGP' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_de='Nakfa',cu_sub_name_de='',cu_iso_3='ERN' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_de='Birr',cu_sub_name_de='',cu_iso_3='ETB' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_de='Euro',cu_sub_name_de='',cu_iso_3='EUR' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_de='Fidschi Dollar',cu_sub_name_de='',cu_iso_3='FJD' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_de='Falkland Pfund',cu_sub_name_de='',cu_iso_3='FKP' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_de='Pfund Sterling',cu_sub_name_de='',cu_iso_3='GBP' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_de='Georgischer Lari',cu_sub_name_de='',cu_iso_3='GEL' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_de='Cedi',cu_sub_name_de='',cu_iso_3='GHC' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_de='Gibraltar Pfund',cu_sub_name_de='',cu_iso_3='GIP' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_de='Dalasi',cu_sub_name_de='',cu_iso_3='GMD' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_de='Guinea Franc',cu_sub_name_de='',cu_iso_3='GNF' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_de='Quetzal',cu_sub_name_de='',cu_iso_3='GTQ' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_de='Guinea Bissau Peso',cu_sub_name_de='',cu_iso_3='GWP' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_de='Guyana Dollar',cu_sub_name_de='',cu_iso_3='GYD' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_de='Hongkong Dollar',cu_sub_name_de='',cu_iso_3='HKD' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_de='Lempira',cu_sub_name_de='',cu_iso_3='HNL' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_de='Kuna',cu_sub_name_de='',cu_iso_3='HRK' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_de='Gourde',cu_sub_name_de='',cu_iso_3='HTG' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_de='Forint',cu_sub_name_de='',cu_iso_3='HUF' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_de='Rupiah',cu_sub_name_de='',cu_iso_3='IDR' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_de='Schekel',cu_sub_name_de='',cu_iso_3='ILS' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_de='Indische Rupie',cu_sub_name_de='',cu_iso_3='INR' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_de='Irak Dinar',cu_sub_name_de='',cu_iso_3='IQD' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_de='Rial',cu_sub_name_de='',cu_iso_3='IRR' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_de='Isländische Krone',cu_sub_name_de='',cu_iso_3='ISK' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_de='Jamaika Dollar',cu_sub_name_de='',cu_iso_3='JMD' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_de='Jordanischer Dinar',cu_sub_name_de='',cu_iso_3='JOD' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_de='Yen',cu_sub_name_de='',cu_iso_3='JPY' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_de='Kenia Schilling',cu_sub_name_de='',cu_iso_3='KES' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_de='Som',cu_sub_name_de='',cu_iso_3='KGS' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_de='Riel',cu_sub_name_de='',cu_iso_3='KHR' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_de='Komoren Franc',cu_sub_name_de='',cu_iso_3='KMF' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_de='Nordkoreanischer Won',cu_sub_name_de='',cu_iso_3='KPW' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_de='Südkoreanischer Won',cu_sub_name_de='',cu_iso_3='KRW' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_de='Kuwait Dinar',cu_sub_name_de='',cu_iso_3='KWD' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_de='Kaiman-Dollar',cu_sub_name_de='',cu_iso_3='KYD' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_de='Tenge',cu_sub_name_de='',cu_iso_3='KZT' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_de='Kip',cu_sub_name_de='',cu_iso_3='LAK' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_de='Libanesisches Pfund',cu_sub_name_de='',cu_iso_3='LBP' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_de='Sri Lanka Rupie',cu_sub_name_de='',cu_iso_3='LKR' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_de='Liberianischer Dollar',cu_sub_name_de='',cu_iso_3='LRD' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_de='Loti',cu_sub_name_de='',cu_iso_3='LSL' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_de='Litauischer Litas',cu_sub_name_de='',cu_iso_3='LTL' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_de='Lettischer Lats',cu_sub_name_de='',cu_iso_3='LVL' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_de='Libyscher Dinar',cu_sub_name_de='',cu_iso_3='LYD' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_de='Marokkanischer Dirham',cu_sub_name_de='',cu_iso_3='MAD' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_de='Moldau Leu',cu_sub_name_de='',cu_iso_3='MDL' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_de='Denar',cu_sub_name_de='',cu_iso_3='MKD' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_de='Kyat',cu_sub_name_de='',cu_iso_3='MMK' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_de='Tugrik',cu_sub_name_de='',cu_iso_3='MNT' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_de='Pataca',cu_sub_name_de='',cu_iso_3='MOP' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_de='Ouguiya',cu_sub_name_de='',cu_iso_3='MRO' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_de='Maltesische Lira',cu_sub_name_de='',cu_iso_3='MTL' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_de='Mauritius Rupie',cu_sub_name_de='',cu_iso_3='MUR' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_de='Rufiyaa',cu_sub_name_de='',cu_iso_3='MVR' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_de='Malawi Kwacha',cu_sub_name_de='',cu_iso_3='MWK' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_de='Mexikanischer Peso',cu_sub_name_de='',cu_iso_3='MXN' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_de='Malaysischer Ringgit',cu_sub_name_de='',cu_iso_3='MYR' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_de='Metical',cu_sub_name_de='',cu_iso_3='MZM' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_de='Namibia Dollar',cu_sub_name_de='',cu_iso_3='NAD' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_de='Naira',cu_sub_name_de='',cu_iso_3='NGN' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_de='Gold-Cordoba',cu_sub_name_de='',cu_iso_3='NIO' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_de='Norwegische Krone',cu_sub_name_de='',cu_iso_3='NOK' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_de='Nepalesische Rupie',cu_sub_name_de='',cu_iso_3='NPR' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_de='Neuseeland Dollar',cu_sub_name_de='',cu_iso_3='NZD' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_de='Rial Omani',cu_sub_name_de='',cu_iso_3='OMR' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_de='Balboa',cu_sub_name_de='',cu_iso_3='PAB' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_de='Neuer Sol',cu_sub_name_de='',cu_iso_3='PEN' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_de='Kina',cu_sub_name_de='',cu_iso_3='PGK' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_de='Philippinischer Peso',cu_sub_name_de='',cu_iso_3='PHP' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_de='Pakistanische Rupie',cu_sub_name_de='',cu_iso_3='PKR' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_de='Zloty',cu_sub_name_de='',cu_iso_3='PLN' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_de='Guarani',cu_sub_name_de='',cu_iso_3='PYG' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_de='Katar Riyal',cu_sub_name_de='',cu_iso_3='QAR' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_de='Leu',cu_sub_name_de='',cu_iso_3='ROL' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_de='Russischer Rubel (neu)',cu_sub_name_de='',cu_iso_3='RUB' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_de='Ruanda Franc',cu_sub_name_de='',cu_iso_3='RWF' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_de='Saudi Riyal',cu_sub_name_de='',cu_iso_3='SAR' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_de='Salomonen Dollar',cu_sub_name_de='',cu_iso_3='SBD' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_de='Seychellen Rupie',cu_sub_name_de='',cu_iso_3='SCR' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_de='Sudanesischer Dinar',cu_sub_name_de='',cu_iso_3='SDD' WHERE cu_iso_3='SDD';
UPDATE static_currencies SET cu_name_de='Schwedische Krone',cu_sub_name_de='',cu_iso_3='SEK' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_de='Singapur Dollar',cu_sub_name_de='',cu_iso_3='SGD' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_de='St. Helena Pfund',cu_sub_name_de='',cu_iso_3='SHP' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_de='Tolar',cu_sub_name_de='',cu_iso_3='SIT' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_de='Slowakische Krone',cu_sub_name_de='',cu_iso_3='SKK' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_de='Leone',cu_sub_name_de='',cu_iso_3='SLL' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_de='Somalia Schilling',cu_sub_name_de='',cu_iso_3='SOS' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_de='Dobra',cu_sub_name_de='',cu_iso_3='STD' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_de='El Salvador Colon',cu_sub_name_de='',cu_iso_3='SVC' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_de='Syrisches Pfund',cu_sub_name_de='',cu_iso_3='SYP' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_de='Lilangeni',cu_sub_name_de='',cu_iso_3='SZL' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_de='Baht',cu_sub_name_de='',cu_iso_3='THB' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_de='Tadschikistan Somoni',cu_sub_name_de='',cu_iso_3='TJS' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_de='Turkmenistan-Manat',cu_sub_name_de='',cu_iso_3='TMM' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_de='Tunesischer Dinar',cu_sub_name_de='',cu_iso_3='TND' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_de='Paʻanga',cu_sub_name_de='',cu_iso_3='TOP' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_de='Trinidad und Tobago Dollar',cu_sub_name_de='',cu_iso_3='TTD' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_de='Neuer Taiwan Dollar',cu_sub_name_de='',cu_iso_3='TWD' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_de='Tansania Schilling',cu_sub_name_de='',cu_iso_3='TZS' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_de='Hryvnia',cu_sub_name_de='',cu_iso_3='UAH' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_de='Uganda Schilling',cu_sub_name_de='',cu_iso_3='UGX' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_de='US Dollar',cu_sub_name_de='',cu_iso_3='USD' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_de='Uruguayischer Peso',cu_sub_name_de='',cu_iso_3='UYU' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_de='Usbekistan Sum',cu_sub_name_de='',cu_iso_3='UZS' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_de='Bolivar',cu_sub_name_de='',cu_iso_3='VEB' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_de='Dong',cu_sub_name_de='',cu_iso_3='VND' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_de='Vatu',cu_sub_name_de='',cu_iso_3='VUV' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_de='Tala',cu_sub_name_de='',cu_iso_3='WST' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_de='CFA Franc (Äquatorial)',cu_sub_name_de='',cu_iso_3='XAF' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_de='Ostkaribischer Dollar',cu_sub_name_de='',cu_iso_3='XCD' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_de='CFA Franc (West)',cu_sub_name_de='',cu_iso_3='XOF' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_de='CFP Franc',cu_sub_name_de='',cu_iso_3='XPF' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_de='Jemen Rial',cu_sub_name_de='',cu_iso_3='YER' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_de='Rand',cu_sub_name_de='',cu_iso_3='ZAR' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_de='Kwacha',cu_sub_name_de='',cu_iso_3='ZMK' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_de='Simbabwe Dollar',cu_sub_name_de='',cu_iso_3='ZWD' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_de='Afghani',cu_sub_name_de='',cu_iso_3='AFN' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_de='',cu_sub_name_de='',cu_iso_3='CSD' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_de='Madagaskar Ariary',cu_sub_name_de='',cu_iso_3='MGA' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_de='',cu_sub_name_de='',cu_iso_3='SRD' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_de='Neue Türkische Lira',cu_sub_name_de='',cu_iso_3='TRY' WHERE cu_iso_3='TRY';


## static_languages
UPDATE static_languages SET lg_name_de='Abchasisch',lg_iso_2='AB' WHERE lg_iso_2='AB';
UPDATE static_languages SET lg_name_de='Afar',lg_iso_2='AA' WHERE lg_iso_2='AA';
UPDATE static_languages SET lg_name_de='Afrikaans',lg_iso_2='AF' WHERE lg_iso_2='AF';
UPDATE static_languages SET lg_name_de='Albanisch',lg_iso_2='SQ' WHERE lg_iso_2='SQ';
UPDATE static_languages SET lg_name_de='Amharisch',lg_iso_2='AM' WHERE lg_iso_2='AM';
UPDATE static_languages SET lg_name_de='Arabisch',lg_iso_2='AR' WHERE lg_iso_2='AR';
UPDATE static_languages SET lg_name_de='Armenisch',lg_iso_2='HY' WHERE lg_iso_2='HY';
UPDATE static_languages SET lg_name_de='Assamesisch',lg_iso_2='AS' WHERE lg_iso_2='AS';
UPDATE static_languages SET lg_name_de='Aymará-Sprache',lg_iso_2='AY' WHERE lg_iso_2='AY';
UPDATE static_languages SET lg_name_de='Aserbaidschanisch',lg_iso_2='AZ' WHERE lg_iso_2='AZ';
UPDATE static_languages SET lg_name_de='Baschkirisch',lg_iso_2='BA' WHERE lg_iso_2='BA';
UPDATE static_languages SET lg_name_de='Baskisch',lg_iso_2='EU' WHERE lg_iso_2='EU';
UPDATE static_languages SET lg_name_de='Bengalisch',lg_iso_2='BN' WHERE lg_iso_2='BN';
UPDATE static_languages SET lg_name_de='Bhutanisch',lg_iso_2='DZ' WHERE lg_iso_2='DZ';
UPDATE static_languages SET lg_name_de='Biharisch',lg_iso_2='BH' WHERE lg_iso_2='BH';
UPDATE static_languages SET lg_name_de='Bislama',lg_iso_2='BI' WHERE lg_iso_2='BI';
UPDATE static_languages SET lg_name_de='Bretonisch',lg_iso_2='BR' WHERE lg_iso_2='BR';
UPDATE static_languages SET lg_name_de='Bulgarisch',lg_iso_2='BG' WHERE lg_iso_2='BG';
UPDATE static_languages SET lg_name_de='Birmanisch',lg_iso_2='MY' WHERE lg_iso_2='MY';
UPDATE static_languages SET lg_name_de='Weißrussisch',lg_iso_2='BE' WHERE lg_iso_2='BE';
UPDATE static_languages SET lg_name_de='Kambodschanisch',lg_iso_2='KM' WHERE lg_iso_2='KM';
UPDATE static_languages SET lg_name_de='Katalanisch',lg_iso_2='CA' WHERE lg_iso_2='CA';
UPDATE static_languages SET lg_name_de='Zhuang',lg_iso_2='ZA' WHERE lg_iso_2='ZA';
UPDATE static_languages SET lg_name_de='Chinesisch',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_de='Korsisch',lg_iso_2='CO' WHERE lg_iso_2='CO';
UPDATE static_languages SET lg_name_de='Kroatisch',lg_iso_2='HR' WHERE lg_iso_2='HR';
UPDATE static_languages SET lg_name_de='Tschechisch',lg_iso_2='CS' WHERE lg_iso_2='CS';
UPDATE static_languages SET lg_name_de='Dänisch',lg_iso_2='DA' WHERE lg_iso_2='DA';
UPDATE static_languages SET lg_name_de='Niederländisch',lg_iso_2='NL' WHERE lg_iso_2='NL';
UPDATE static_languages SET lg_name_de='Englisch',lg_iso_2='EN' WHERE lg_iso_2='EN';
UPDATE static_languages SET lg_name_de='Esperanto',lg_iso_2='EO' WHERE lg_iso_2='EO';
UPDATE static_languages SET lg_name_de='Estnisch',lg_iso_2='ET' WHERE lg_iso_2='ET';
UPDATE static_languages SET lg_name_de='Färöisch',lg_iso_2='FO' WHERE lg_iso_2='FO';
UPDATE static_languages SET lg_name_de='Persisch',lg_iso_2='FA' WHERE lg_iso_2='FA';
UPDATE static_languages SET lg_name_de='Fidschianisch',lg_iso_2='FJ' WHERE lg_iso_2='FJ';
UPDATE static_languages SET lg_name_de='Finnisch',lg_iso_2='FI' WHERE lg_iso_2='FI';
UPDATE static_languages SET lg_name_de='Französisch',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_de='Friesisch',lg_iso_2='FY' WHERE lg_iso_2='FY';
UPDATE static_languages SET lg_name_de='Galizisch',lg_iso_2='GL' WHERE lg_iso_2='GL';
UPDATE static_languages SET lg_name_de='Schottisch-Gälisch',lg_iso_2='GD' WHERE lg_iso_2='GD';
UPDATE static_languages SET lg_name_de='Manx',lg_iso_2='GV' WHERE lg_iso_2='GV';
UPDATE static_languages SET lg_name_de='Georgisch',lg_iso_2='KA' WHERE lg_iso_2='KA';
UPDATE static_languages SET lg_name_de='Deutsch',lg_iso_2='DE' WHERE lg_iso_2='DE';
UPDATE static_languages SET lg_name_de='Griechisch',lg_iso_2='EL' WHERE lg_iso_2='EL';
UPDATE static_languages SET lg_name_de='Grönländisch',lg_iso_2='KL' WHERE lg_iso_2='KL';
UPDATE static_languages SET lg_name_de='Guarani',lg_iso_2='GN' WHERE lg_iso_2='GN';
UPDATE static_languages SET lg_name_de='Gujarati',lg_iso_2='GU' WHERE lg_iso_2='GU';
UPDATE static_languages SET lg_name_de='Hausa',lg_iso_2='HA' WHERE lg_iso_2='HA';
UPDATE static_languages SET lg_name_de='Hebräisch',lg_iso_2='HE' WHERE lg_iso_2='HE';
UPDATE static_languages SET lg_name_de='Hindi',lg_iso_2='HI' WHERE lg_iso_2='HI';
UPDATE static_languages SET lg_name_de='Ungarisch',lg_iso_2='HU' WHERE lg_iso_2='HU';
UPDATE static_languages SET lg_name_de='Isländisch',lg_iso_2='IS' WHERE lg_iso_2='IS';
UPDATE static_languages SET lg_name_de='Indonesisch',lg_iso_2='ID' WHERE lg_iso_2='ID';
UPDATE static_languages SET lg_name_de='Interlingua',lg_iso_2='IA' WHERE lg_iso_2='IA';
UPDATE static_languages SET lg_name_de='Interlingue',lg_iso_2='IE' WHERE lg_iso_2='IE';
UPDATE static_languages SET lg_name_de='Inukitut',lg_iso_2='IU' WHERE lg_iso_2='IU';
UPDATE static_languages SET lg_name_de='Inupiak',lg_iso_2='IK' WHERE lg_iso_2='IK';
UPDATE static_languages SET lg_name_de='Irisch',lg_iso_2='GA' WHERE lg_iso_2='GA';
UPDATE static_languages SET lg_name_de='Italienisch',lg_iso_2='IT' WHERE lg_iso_2='IT';
UPDATE static_languages SET lg_name_de='Japanisch',lg_iso_2='JA' WHERE lg_iso_2='JA';
UPDATE static_languages SET lg_name_de='Kannada',lg_iso_2='KN' WHERE lg_iso_2='KN';
UPDATE static_languages SET lg_name_de='Kaschmirisch',lg_iso_2='KS' WHERE lg_iso_2='KS';
UPDATE static_languages SET lg_name_de='Kasachisch',lg_iso_2='KK' WHERE lg_iso_2='KK';
UPDATE static_languages SET lg_name_de='Ruandisch',lg_iso_2='RW' WHERE lg_iso_2='RW';
UPDATE static_languages SET lg_name_de='Kirgisisch',lg_iso_2='KY' WHERE lg_iso_2='KY';
UPDATE static_languages SET lg_name_de='Rundi-Sprache',lg_iso_2='RN' WHERE lg_iso_2='RN';
UPDATE static_languages SET lg_name_de='Koreanisch',lg_iso_2='KO' WHERE lg_iso_2='KO';
UPDATE static_languages SET lg_name_de='Kurdisch',lg_iso_2='KU' WHERE lg_iso_2='KU';
UPDATE static_languages SET lg_name_de='Laotisch',lg_iso_2='LO' WHERE lg_iso_2='LO';
UPDATE static_languages SET lg_name_de='Latein',lg_iso_2='LA' WHERE lg_iso_2='LA';
UPDATE static_languages SET lg_name_de='Lettisch',lg_iso_2='LV' WHERE lg_iso_2='LV';
UPDATE static_languages SET lg_name_de='Lingala',lg_iso_2='LN' WHERE lg_iso_2='LN';
UPDATE static_languages SET lg_name_de='Litauisch',lg_iso_2='LT' WHERE lg_iso_2='LT';
UPDATE static_languages SET lg_name_de='Mazedonisch',lg_iso_2='MK' WHERE lg_iso_2='MK';
UPDATE static_languages SET lg_name_de='Madagassisch',lg_iso_2='MG' WHERE lg_iso_2='MG';
UPDATE static_languages SET lg_name_de='Malaiisch',lg_iso_2='MS' WHERE lg_iso_2='MS';
UPDATE static_languages SET lg_name_de='Malayalam',lg_iso_2='ML' WHERE lg_iso_2='ML';
UPDATE static_languages SET lg_name_de='Maltesisch',lg_iso_2='MT' WHERE lg_iso_2='MT';
UPDATE static_languages SET lg_name_de='Maori',lg_iso_2='MI' WHERE lg_iso_2='MI';
UPDATE static_languages SET lg_name_de='Marathi',lg_iso_2='MR' WHERE lg_iso_2='MR';
UPDATE static_languages SET lg_name_de='Moldauisch',lg_iso_2='MO' WHERE lg_iso_2='MO';
UPDATE static_languages SET lg_name_de='Mongolisch',lg_iso_2='MN' WHERE lg_iso_2='MN';
UPDATE static_languages SET lg_name_de='Nauruisch',lg_iso_2='NA' WHERE lg_iso_2='NA';
UPDATE static_languages SET lg_name_de='Nepalesisch',lg_iso_2='NE' WHERE lg_iso_2='NE';
UPDATE static_languages SET lg_name_de='Norwegisch',lg_iso_2='NO' WHERE lg_iso_2='NO';
UPDATE static_languages SET lg_name_de='Okzitanisch',lg_iso_2='OC' WHERE lg_iso_2='OC';
UPDATE static_languages SET lg_name_de='Orija',lg_iso_2='OR' WHERE lg_iso_2='OR';
UPDATE static_languages SET lg_name_de='Oromo',lg_iso_2='OM' WHERE lg_iso_2='OM';
UPDATE static_languages SET lg_name_de='Afghanisch (Paschtu)',lg_iso_2='PS' WHERE lg_iso_2='PS';
UPDATE static_languages SET lg_name_de='Polnisch',lg_iso_2='PL' WHERE lg_iso_2='PL';
UPDATE static_languages SET lg_name_de='Portugiesisch',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_de='Pandschabisch',lg_iso_2='PA' WHERE lg_iso_2='PA';
UPDATE static_languages SET lg_name_de='Quechua',lg_iso_2='QU' WHERE lg_iso_2='QU';
UPDATE static_languages SET lg_name_de='Rätoromanisch',lg_iso_2='RM' WHERE lg_iso_2='RM';
UPDATE static_languages SET lg_name_de='Rumänisch',lg_iso_2='RO' WHERE lg_iso_2='RO';
UPDATE static_languages SET lg_name_de='Russisch',lg_iso_2='RU' WHERE lg_iso_2='RU';
UPDATE static_languages SET lg_name_de='Samoanisch',lg_iso_2='SM' WHERE lg_iso_2='SM';
UPDATE static_languages SET lg_name_de='Sango',lg_iso_2='SG' WHERE lg_iso_2='SG';
UPDATE static_languages SET lg_name_de='Sanskrit',lg_iso_2='SA' WHERE lg_iso_2='SA';
UPDATE static_languages SET lg_name_de='Serbisch',lg_iso_2='SR' WHERE lg_iso_2='SR';
UPDATE static_languages SET lg_name_de='Süd-Sotho-Sprache',lg_iso_2='ST' WHERE lg_iso_2='ST';
UPDATE static_languages SET lg_name_de='Tswana-Sprache',lg_iso_2='TN' WHERE lg_iso_2='TN';
UPDATE static_languages SET lg_name_de='Shona',lg_iso_2='SN' WHERE lg_iso_2='SN';
UPDATE static_languages SET lg_name_de='Sindhi',lg_iso_2='SD' WHERE lg_iso_2='SD';
UPDATE static_languages SET lg_name_de='Singhalesisch',lg_iso_2='SI' WHERE lg_iso_2='SI';
UPDATE static_languages SET lg_name_de='Swazi',lg_iso_2='SS' WHERE lg_iso_2='SS';
UPDATE static_languages SET lg_name_de='Slowakisch',lg_iso_2='SK' WHERE lg_iso_2='SK';
UPDATE static_languages SET lg_name_de='Slowenisch',lg_iso_2='SL' WHERE lg_iso_2='SL';
UPDATE static_languages SET lg_name_de='Somali',lg_iso_2='SO' WHERE lg_iso_2='SO';
UPDATE static_languages SET lg_name_de='Spanisch',lg_iso_2='ES' WHERE lg_iso_2='ES';
UPDATE static_languages SET lg_name_de='Sudanesisch',lg_iso_2='SU' WHERE lg_iso_2='SU';
UPDATE static_languages SET lg_name_de='Suaheli',lg_iso_2='SW' WHERE lg_iso_2='SW';
UPDATE static_languages SET lg_name_de='Schwedisch',lg_iso_2='SV' WHERE lg_iso_2='SV';
UPDATE static_languages SET lg_name_de='Tagalog',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_de='Tadschikisch',lg_iso_2='TG' WHERE lg_iso_2='TG';
UPDATE static_languages SET lg_name_de='Tamilisch',lg_iso_2='TA' WHERE lg_iso_2='TA';
UPDATE static_languages SET lg_name_de='Tatarisch',lg_iso_2='TT' WHERE lg_iso_2='TT';
UPDATE static_languages SET lg_name_de='Telugu',lg_iso_2='TE' WHERE lg_iso_2='TE';
UPDATE static_languages SET lg_name_de='Thai',lg_iso_2='TH' WHERE lg_iso_2='TH';
UPDATE static_languages SET lg_name_de='Tibetisch',lg_iso_2='BO' WHERE lg_iso_2='BO';
UPDATE static_languages SET lg_name_de='Tigrinja',lg_iso_2='TI' WHERE lg_iso_2='TI';
UPDATE static_languages SET lg_name_de='Tongaisch',lg_iso_2='TO' WHERE lg_iso_2='TO';
UPDATE static_languages SET lg_name_de='Tsonga',lg_iso_2='TS' WHERE lg_iso_2='TS';
UPDATE static_languages SET lg_name_de='Türkisch',lg_iso_2='TR' WHERE lg_iso_2='TR';
UPDATE static_languages SET lg_name_de='Turkmenisch',lg_iso_2='TK' WHERE lg_iso_2='TK';
UPDATE static_languages SET lg_name_de='Twi',lg_iso_2='TW' WHERE lg_iso_2='TW';
UPDATE static_languages SET lg_name_de='Uigurisch',lg_iso_2='UG' WHERE lg_iso_2='UG';
UPDATE static_languages SET lg_name_de='Ukrainisch',lg_iso_2='UK' WHERE lg_iso_2='UK';
UPDATE static_languages SET lg_name_de='Urdu',lg_iso_2='UR' WHERE lg_iso_2='UR';
UPDATE static_languages SET lg_name_de='Usbekisch',lg_iso_2='UZ' WHERE lg_iso_2='UZ';
UPDATE static_languages SET lg_name_de='Vietnamesisch',lg_iso_2='VI' WHERE lg_iso_2='VI';
UPDATE static_languages SET lg_name_de='Volapük',lg_iso_2='VO' WHERE lg_iso_2='VO';
UPDATE static_languages SET lg_name_de='Kymrisch',lg_iso_2='CY' WHERE lg_iso_2='CY';
UPDATE static_languages SET lg_name_de='Wolof',lg_iso_2='WO' WHERE lg_iso_2='WO';
UPDATE static_languages SET lg_name_de='Xhosa',lg_iso_2='XH' WHERE lg_iso_2='XH';
UPDATE static_languages SET lg_name_de='Jiddisch',lg_iso_2='YI' WHERE lg_iso_2='YI';
UPDATE static_languages SET lg_name_de='Joruba',lg_iso_2='YO' WHERE lg_iso_2='YO';
UPDATE static_languages SET lg_name_de='Zulu',lg_iso_2='ZU' WHERE lg_iso_2='ZU';
UPDATE static_languages SET lg_name_de='Bosnisch',lg_iso_2='BS' WHERE lg_iso_2='BS';
UPDATE static_languages SET lg_name_de='Avestisch',lg_iso_2='AE' WHERE lg_iso_2='AE';
UPDATE static_languages SET lg_name_de='Akan',lg_iso_2='AK' WHERE lg_iso_2='AK';
UPDATE static_languages SET lg_name_de='Aragonesisch',lg_iso_2='AN' WHERE lg_iso_2='AN';
UPDATE static_languages SET lg_name_de='Awarisch',lg_iso_2='AV' WHERE lg_iso_2='AV';
UPDATE static_languages SET lg_name_de='Bambara-Sprache',lg_iso_2='BM' WHERE lg_iso_2='BM';
UPDATE static_languages SET lg_name_de='Tschetschenisch',lg_iso_2='CE' WHERE lg_iso_2='CE';
UPDATE static_languages SET lg_name_de='Chamorro-Sprache',lg_iso_2='CH' WHERE lg_iso_2='CH';
UPDATE static_languages SET lg_name_de='Cree',lg_iso_2='CR' WHERE lg_iso_2='CR';
UPDATE static_languages SET lg_name_de='Kirchenslawisch',lg_iso_2='CU' WHERE lg_iso_2='CU';
UPDATE static_languages SET lg_name_de='Tschuwaschisch',lg_iso_2='CV' WHERE lg_iso_2='CV';
UPDATE static_languages SET lg_name_de='Maledivisch',lg_iso_2='DV' WHERE lg_iso_2='DV';
UPDATE static_languages SET lg_name_de='Ewe-Sprache',lg_iso_2='EE' WHERE lg_iso_2='EE';
UPDATE static_languages SET lg_name_de='Ful',lg_iso_2='FF' WHERE lg_iso_2='FF';
UPDATE static_languages SET lg_name_de='Hiri-Motu',lg_iso_2='HO' WHERE lg_iso_2='HO';
UPDATE static_languages SET lg_name_de='Kreolisch',lg_iso_2='HT' WHERE lg_iso_2='HT';
UPDATE static_languages SET lg_name_de='Herero-Sprache',lg_iso_2='HZ' WHERE lg_iso_2='HZ';
UPDATE static_languages SET lg_name_de='Igbo-Sprache',lg_iso_2='IG' WHERE lg_iso_2='IG';
UPDATE static_languages SET lg_name_de='Sichuan Yi',lg_iso_2='II' WHERE lg_iso_2='II';
UPDATE static_languages SET lg_name_de='Ido-Sprache',lg_iso_2='IO' WHERE lg_iso_2='IO';
UPDATE static_languages SET lg_name_de='Javanisch',lg_iso_2='JV' WHERE lg_iso_2='JV';
UPDATE static_languages SET lg_name_de='Kongo',lg_iso_2='KG' WHERE lg_iso_2='KG';
UPDATE static_languages SET lg_name_de='Kikuyu-Sprache',lg_iso_2='KI' WHERE lg_iso_2='KI';
UPDATE static_languages SET lg_name_de='Kwanyama',lg_iso_2='KJ' WHERE lg_iso_2='KJ';
UPDATE static_languages SET lg_name_de='Kanuri-Sprache',lg_iso_2='KR' WHERE lg_iso_2='KR';
UPDATE static_languages SET lg_name_de='Komi-Sprache',lg_iso_2='KV' WHERE lg_iso_2='KV';
UPDATE static_languages SET lg_name_de='Kornisch',lg_iso_2='KW' WHERE lg_iso_2='KW';
UPDATE static_languages SET lg_name_de='Luxemburgisch',lg_iso_2='LB' WHERE lg_iso_2='LB';
UPDATE static_languages SET lg_name_de='Ganda-Sprache',lg_iso_2='LG' WHERE lg_iso_2='LG';
UPDATE static_languages SET lg_name_de='Limburgisch',lg_iso_2='LI' WHERE lg_iso_2='LI';
UPDATE static_languages SET lg_name_de='Luba',lg_iso_2='LU' WHERE lg_iso_2='LU';
UPDATE static_languages SET lg_name_de='Marschallesisch',lg_iso_2='MH' WHERE lg_iso_2='MH';
UPDATE static_languages SET lg_name_de='Norwegisch Bokmål',lg_iso_2='NB' WHERE lg_iso_2='NB';
UPDATE static_languages SET lg_name_de='Ndebele-Sprache (Nord)',lg_iso_2='ND' WHERE lg_iso_2='ND';
UPDATE static_languages SET lg_name_de='Ndonga',lg_iso_2='NG' WHERE lg_iso_2='NG';
UPDATE static_languages SET lg_name_de='Norwegisch Nynorsk',lg_iso_2='NN' WHERE lg_iso_2='NN';
UPDATE static_languages SET lg_name_de='Ndebele-Sprache (Süd)',lg_iso_2='NR' WHERE lg_iso_2='NR';
UPDATE static_languages SET lg_name_de='Navajo-Sprache',lg_iso_2='NV' WHERE lg_iso_2='NV';
UPDATE static_languages SET lg_name_de='Chewa-Sprache',lg_iso_2='NY' WHERE lg_iso_2='NY';
UPDATE static_languages SET lg_name_de='Ojibwa-Sprache',lg_iso_2='OJ' WHERE lg_iso_2='OJ';
UPDATE static_languages SET lg_name_de='Ossetisch',lg_iso_2='OS' WHERE lg_iso_2='OS';
UPDATE static_languages SET lg_name_de='Pali',lg_iso_2='PI' WHERE lg_iso_2='PI';
UPDATE static_languages SET lg_name_de='Sardisch',lg_iso_2='SC' WHERE lg_iso_2='SC';
UPDATE static_languages SET lg_name_de='Nord-Samisch',lg_iso_2='SE' WHERE lg_iso_2='SE';
UPDATE static_languages SET lg_name_de='Serbo-Kroatisch',lg_iso_2='SH' WHERE lg_iso_2='SH';
UPDATE static_languages SET lg_name_de='Tahitisch',lg_iso_2='TY' WHERE lg_iso_2='TY';
UPDATE static_languages SET lg_name_de='Venda-Sprache',lg_iso_2='VE' WHERE lg_iso_2='VE';
UPDATE static_languages SET lg_name_de='Wallonisch',lg_iso_2='WA' WHERE lg_iso_2='WA';


